name: Run Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install Python dependencies
      run: pip install -e .[test,transformers,torch,tensorflow]
    - name: Run Unit Tests
      run: make unit-test
    # - name: Run Integration Tests
    #   run: make integ-test